# Generated by Django 3.1.7 on 2021-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterField(
            model_name='fuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
